PruebasWebNetCore/PruebasWebNetCore.Web/Controllers/ColoresController.cs
namespace PruebasWebNetCore.Web.Controllers
{
    using Data.Entities;
    using Data.Repositories;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using PruebasWebNetCore.Web.Helpers;
    using PruebasWebNetCore.Web.Models;
    using System.IO;
    using System.Threading.Tasks;

    public class ColoresController : Controller
    {
        private readonly IColorRepository colorRepository;

        public ColoresController(IColorRepository colorRepository)
        {
            this.colorRepository = colorRepository;
        }

        // GET
        public IActionResult Index()
        {
            return View(this.colorRepository.GetAll());
        }

        // GET
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ColorNotFound");
            }

            var color = await this.colorRepository.GetByIdAsync(id.Value);
            if (color == null)
            {
                return new NotFoundViewResult("ColorNotFound");
            }

            return View(color);
        }

        // GET
        public IActionResult Create()
        {
            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ColorViewModel view)
        {
            if (ModelState.IsValid)
            {
                //para la imagen
                var path = string.Empty;

                if (view.ImagenFile != null && view.ImagenFile.Length > 0)
                {
                    path = Path.Combine(Directory.GetCurrentDirectory(),
                        "wwwroot\\images\\Colores",
                        view.ImagenFile.FileName);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await view.ImagenFile.CopyToAsync(stream);
                    }

                    path = $"~/images/Colores/{view.ImagenFile.FileName}";
                }


                var color = this.ToColor(view, path);

                await this.colorRepository.CreateAsync(color);
                return RedirectToAction(nameof(Index));
            }
            return View(view);
        }


        //buscar otra forma de hacer esto
        private Color ToColor(ColorViewModel view, string path)
        {
            return new Color
            {
                Id = view.Id,
                ImagenUrl = path,
                Nombre = view.Nombre,
                Codigo = view.Codigo,
                Estado = view.Estado
            };
        }

        // GET
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var color = await this.colorRepository.GetByIdAsync(id.Value);
            if (color == null)
            {
                return NotFound();
            }

            var view = this.ToColorViewModel(color);

            return View(view);
        }

        private ColorViewModel ToColorViewModel(Color color)
        {
            return new ColorViewModel
            {
                Id = color.Id,
                ImagenUrl = color.ImagenUrl,
                Nombre = color.Nombre,
                Codigo = color.Codigo,
                Estado = color.Estado
            };
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ColorViewModel view)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var path = view.ImagenUrl;

                    if (view.ImagenFile != null && view.ImagenFile.Length > 0)
                    {
                        path = Path.Combine(Directory.GetCurrentDirectory(),
                            "wwwroot\\images\\Colores",
                            view.ImagenFile.FileName);

                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            await view.ImagenFile.CopyToAsync(stream);
                        }

                        path = $"~/images/Colores/{view.ImagenFile.FileName}";
                    }


                    var color = this.ToColor(view, path);
                    await this.colorRepository.UpdateAsync(color);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await this.colorRepository.ExistAsync(view.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(view);
        }

        // GET
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var color = await this.colorRepository.GetByIdAsync(id.Value);
            if (color == null)
            {
                return NotFound();
            }

            return View(color);
        }

        // POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var color = await this.colorRepository.GetByIdAsync(id);
            await this.colorRepository.DeleteAsync(color);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult ColorNotFound()
        {
            return this.View();
        }

    }
}

PruebasWebNetCore/PruebasWebNetCore.Web/Controllers/CountriesController.cs
namespace PruebasWebNetCore.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using PruebasWebNetCore.Web.Data.Entities;
    using PruebasWebNetCore.Web.Data.Repositories;
    using PruebasWebNetCore.Web.Models;
    using System.Threading.Tasks;

    public class CountriesController : Controller
    {
        private readonly ICountryRepository countryRepository;

        public CountriesController(ICountryRepository countryRepository)
        {
            this.countryRepository = countryRepository;
        }

        //
        public async Task<IActionResult> DeleteCity(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var city = await this.countryRepository.GetCityAsync(id.Value);
            if (city == null)
            {
                return NotFound();
            }

            var countryId = await this.countryRepository.DeleteCityAsync(city);
            return this.RedirectToAction("Index");
        }

        public async Task<IActionResult> EditCity(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var city = await this.countryRepository.GetCityAsync(id.Value);
            if (city == null)
            {
                return NotFound();
            }

            return View(city);
        }

        [HttpPost]
        public async Task<IActionResult> EditCity(City city)
        {
            if (this.ModelState.IsValid)
            {
                var countryId = await this.countryRepository.UpdateCityAsync(city);
                if (countryId != 0)
                {
                    return this.RedirectToAction("Index");
                }
            }

            return this.View(city);
        }

        public async Task<IActionResult> AddCity(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await this.countryRepository.GetByIdAsync(id.Value);
            if (country == null)
            {
                return NotFound();
            }

            var model = new CityViewModel { CountryId = country.Id };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddCity(CityViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                await this.countryRepository.AddCityAsync(model);
                //TODO: arreglar esto para que lo mande al pais al que estoy agregando ciudad
                return this.RedirectToAction("Index");
            }

            return this.View(model);
        }


        //
        public IActionResult Index()
        {
            return View(this.countryRepository.GetCountriesWithCities());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await this.countryRepository.GetCountryWithCitiesAsync(id.Value);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Country country)
        {
            if (ModelState.IsValid)
            {
                await this.countryRepository.CreateAsync(country);
                return RedirectToAction(nameof(Index));
            }

            return View(country);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await this.countryRepository.GetByIdAsync(id.Value);
            if (country == null)
            {
                return NotFound();
            }
            return View(country);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Country country)
        {
            if (ModelState.IsValid)
            {
                await this.countryRepository.UpdateAsync(country);
                return RedirectToAction(nameof(Index));
            }

            return View(country);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await this.countryRepository.GetByIdAsync(id.Value);
            if (country == null)
            {
                return NotFound();
            }

            await this.countryRepository.DeleteAsync(country);
            return RedirectToAction(nameof(Index));
        }

    }
}

PruebasWebNetCore/PruebasWebNetCore.Web/Controllers/PedidosController.cs
namespace PruebasWebNetCore.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using PruebasWebNetCore.Web.Data.Repositories;
    using PruebasWebNetCore.Web.Helpers;
    using PruebasWebNetCore.Web.Models;
    using System.Threading.Tasks;

    public class PedidosController : Controller
    {
        private readonly IPedidoRepository pedidoRepository;
        private readonly IEmpresaRepository empresaRepository;
        private readonly IProductoRepository productoRepository;
        private readonly IColorRepository colorRepository;
        private readonly IUserHelper userHelper;

        public PedidosController(IPedidoRepository pedidoRepository, IEmpresaRepository empresaRepository, IProductoRepository productoRepository, IColorRepository colorRepository, IUserHelper userHelper)
        {
            this.pedidoRepository = pedidoRepository;
            this.empresaRepository = empresaRepository;
            this.productoRepository = productoRepository;
            this.colorRepository = colorRepository;
            this.userHelper = userHelper;
        }


        public async Task<IActionResult> AddImpresion(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await this.pedidoRepository.GetByIdAsync(id.Value);
            if (pedido == null)
            {
                return NotFound();
            }

            var model = new ImpresionPedidoViewModel {
                PedidoId = pedido.Id,
                Colores = this.colorRepository.GetComboColors()
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddImpresion(ImpresionPedidoViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                await this.pedidoRepository.AddImpresionAsync(model);
                //TODO: revisar por que esta cosa me da error
                return this.RedirectToAction("Index");
            }

            return this.View(model);
        }

        //para mostrar los pedidos por fase
        public async Task<IActionResult> PedidosDisponibles()
        {
            var user = await this.userHelper.GetUserByEmailAsync(this.User.Identity.Name);

            if (user == null)
            {
                return new NotFoundViewResult("PedidoNotFound");
            }

            if (user.Disponible==true) {
                return View(this.pedidoRepository.GetPedidoPorFase(user));
            }
            else
            {
                //TODO: cambiar esto para que muestre pedido en proceso
                return new NotFoundViewResult("PedidoEnProceso");
            }
        }


        public IActionResult Index()
        {
            return View(this.pedidoRepository.GetPedidoWithAll());

        }

        
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("PedidoNotFound");
            }

            var pedido = await this.pedidoRepository.GetPedidoConImpresionAsync(id.Value);
            if (pedido == null)
            {
                return new NotFoundViewResult("PedidoNotFound");
            }

            return View(pedido);
        }


        //GET
        public IActionResult Create()
        {
            var model = new PedidoViewModel
            {
                //
                Empresas = this.empresaRepository.GetComboEmpresas(),
                Productos = this.productoRepository.GetComboProductos(),
            };
            return View(model);
        }

        // POST: 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PedidoViewModel view)
        {
            if (ModelState.IsValid)
            {
                await this.pedidoRepository.AddPedidoAsync(view);
                return RedirectToAction(nameof(Index));
            }
            return View(view);
        }

        public IActionResult PedidoNotFound()
        {
            return this.View();
        }

        public IActionResult PedidoEnProceso()
        {
            return this.View();
        }



    }
}

PruebasWebNetCore/PruebasWebNetCore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PruebasWebNetCore.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="~/node_modules/font-awesome/css/font-awesome.css" rel="stylesheet"/>   
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>



    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

                @if (this.User.Identity.IsAuthenticated)
                {
                    <div class="collapse navbar-collapse" id="navbarNavDropdown">
                        <ul class="navbar-nav">

                            @if (this.User.IsInRole("Administrador"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Empresas-Proveedores
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" asp-area="" asp-controller="Empresas" asp-action="Index">Gestionar Empresas</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Proveedores" asp-action="Index">Gestionar Proveedores</a>
                                    </div>
                                </li>

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Trabajadores
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" asp-area="" asp-controller="Empleados" asp-action="Index">Gestionar Trabajadores</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Index">Gestionar Cuentas</a>
                                    </div>
                                </li>

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Pedidos
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" asp-area="" asp-controller="Productos" asp-action="Index">Gestionar Productos</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Pedidos" asp-action="Index">Gestionar Pedidos</a>
                                    </div>
                                </li>

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Extras
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" asp-area="" asp-controller="MateriasPrimas" asp-action="Index">Gestionar Materias Primas</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Colores" asp-action="Index">Gestionar Colores</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Countries" asp-action="Index">Gestionar Ciudades</a>
                                    </div>
                                </li>

                            }
                            else
                        if (this.User.IsInRole("Extrusion") || this.User.IsInRole("Impresion") || this.User.IsInRole("Cortado") || this.User.IsInRole("Empaquetado"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Pedidos" asp-action="PedidosDisponibles">Pedidos Disponibles</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="InformacionesFases" asp-action="InformacionFaseActual">Informacion Fase Actual</a>
                                </li>
                            }
                            else
                        if (this.User.IsInRole("EncargadoAlmacenDesechos"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Desechos
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" asp-area="" asp-controller="InformacionesFases" asp-action="DesechosIndex"> Desechos Pendientes</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="AlmacenesDesechos" asp-action="Index"> Inventario Desechos</a>
                                    </div>
                                </li>
                            }

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Almacen Materia Prima
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" asp-area="" asp-controller="AlmacenesMateriasPrimas" asp-action="Index"> Inventario Materia Prima</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="PedidosMateriasPrimas" asp-action="PedidosDeMateriaPrimaEnSolicitud"> Pedidos de Materia Prima</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="PedidosMateriasPrimas" asp-action="Index"> Historial de Pedidos</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="AbastecimientosMateriasPrimas" asp-action="AbastecimientoDeMateriaPrimaEnSolicitud"> Abastecimiento de Materia Prima</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="AbastecimientosMateriasPrimas" asp-action="Index"> Historial de Abastecimiento</a>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Pedido Materia Prima
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" asp-area="" asp-controller="PedidosMateriasPrimas" asp-action="Create"> Solicitar Materia Prima</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="PedidosMateriasPrimas" asp-action="PedidosDeMateriaProcesado"> Pedidos Procesados</a>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Abastecimiento Materia Prima
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" asp-area="" asp-controller="AbastecimientosMateriasPrimas" asp-action="Create"> Abastecer Materia Prima</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="AbastecimientosMateriasPrimas" asp-action="AbastecimientoDeMateriaProcesado"> Abastecimientos Procesados</a>
                                </div>
                            </li>


                        </ul>
                    </div>
                }

                <div>
                    <ul class="nav navbar-nav navbar-right">
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item"><a asp-area="" asp-controller="Account" asp-action="ChangeUser">@this.User.Identity.Name</a></li>
                            <li class="nav-item"><a asp-area="" asp-controller="Account" asp-action="Logout">  Salir</a></li>
                        }
                        else
                        {
                            <li><a asp-area="" asp-controller="Account" asp-action="Login"> Ingresar</a></li>
                        }
                    </ul>
                </div>

           
           
        </nav>
    </header>


    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - PruebasWebNetCore.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>